DOCKER_REGISTRY=nexus3.akraino.org
GERRIT_URL=https://gerrit.akraino.org/r
GIT_URL=ssh://akraino-jobbuilder@gerrit.akraino.org:29418
JENKINS_HOSTNAME=vex-yul-akraino-jenkins-sandbox-1
LOGS_SERVER=https://logs.akraino.org
NEXUS_URL=https://nexus.akraino.org
REGISTRY_PORTS=10001 10002 10003 10004
SILO=sandbox
SONAR_URL=https://sonar.akraino.org
